[application]
out_dir = "docs"

# App (Project) Name
name = "resume"
[web.app.release]
base_path = "Jaghov.github.io/target/dx/resume/release/web/public"
# HTML title tag content
title = "resume"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
