[application]
name = "Jaghov-github-io"

[web.app]
title = "Joseph Aghoghovbia - personal website"
base_path= "Jaghov.github.io"

[web.watcher]
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
